global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'story-geth'
    static_configs:
    - targets:
      - story-geth:6060
    metrics_path: /debug/metrics/prometheus
  - job_name: 'story'
    static_configs:
    - targets:
      - story:26660